spring.application.name=franchise
# Render/Railway will provide the port via an environment variable
server.port=${PORT:8080}

# H2 Configuration
spring.h2.console.enabled=true
# Use a file-based path if the provider allows, otherwise stick to mem
spring.datasource.url=jdbc:h2:mem:franchisedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# CHANGE THIS from 'create' to 'update' for deployment
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true